build(deps): Bump quarkus.version from 3.9.1 to 3.9.2 (#1286)
Bumps `quarkus.version` from 3.9.1 to 3.9.2.
Updates `io.quarkus:quarkus-bom` from 3.9.1 to 3.9.2
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/quarkusio/quarkus/releases">io.quarkus:quarkus-bom's
releases</a>.</em></p>
<blockquote>
<h2>3.9.2</h2>
<h3>Complete changelog</h3>
<ul>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/38964">#38964</a>
- Add smallrye metrics capability</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39668">#39668</a>
- Recompute cache when the redis connection pool is exhausted</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39705">#39705</a>
- WebSockets Next: error handlers part 1</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/39717">#39717</a>
- OIDC code flow access token verification is enforced even if the
application code does not use it as JWT</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39718">#39718</a>
- Enforce OIDC code flow access token verification only if JWT is in the
application code</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39725">#39725</a>
- Setting the correct CodeFlowVerifyAccessTokenDisabledTest test class
name</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39742">#39742</a>
- Fix a remaining reference to quarkus.resteasy-reactive. prefix</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/39746">#39746</a>
- ScheduledExecutorService: cannot remove future task from the
scheduler</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39763">#39763</a>
- WebSockets Next: error handlers part 2</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39766">#39766</a>
- Properly handle array class types to be looked up</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39770">#39770</a>
- Improve the multipart encoded mode handling in the rest client</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/39776">#39776</a>
- Cannot build native image after 3.9.1 upgrade - missing configuration
properties but they exist</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/39777">#39777</a>
- Bean Param init issue - java.lang.NoClassDefFoundError:
io/quarkus/generated/int$quarkusrestparamConverter$</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39790">#39790</a>
- Add quarkus-credentials-deployment where it's missing</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39794">#39794</a>
- Bump org.jboss.threads:jboss-threads from 3.6.0.Final to
3.6.1.Final</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39797">#39797</a>
- Docs: fix typo in OIDC tenant resolution by configuration</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/39798">#39798</a>
- Update documentation for QUARKUS AND GRADLE - Development mode:
quarkusDev#workingDir has been deprecated</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39804">#39804</a>
- Always record profiles</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39823">#39823</a>
- Ensure ParameterConverter is loaded from the TCCL</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39829">#39829</a>
- Use quarkusDev#workingDirectory</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39835">#39835</a>
- Bump maven-model-helper to 36</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/quarkusio/quarkus/commit/69864c3440d97dc19fb7f81459cd445b60a8b777"><code>69864c3</code></a>
[RELEASE] - Bump version to 3.9.2</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/7d4d8e1127d7846add5268ddd88b414c0d7ea1cf"><code>7d4d8e1</code></a>
Merge pull request <a
href="https://redirect.github.com/quarkusio/quarkus/issues/39845">#39845</a>
from gsmet/3.9.2-backports-1</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/cc5ab4b1be581ab30f02a50ac3fa46e1a3f2ff03"><code>cc5ab4b</code></a>
Add smallrye metrics capability</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/93e7782acb7b1531fb798aa930662892d4ce087f"><code>93e7782</code></a>
Bump maven-model-helper to 36</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/4043c0e7f82541cef3cb12cdd376ab76c42ba03d"><code>4043c0e</code></a>
Ensure ParameterConverter is loaded from the TCCL</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/8cdead9234433c58b367f2cf122a73948509bfbb"><code>8cdead9</code></a>
Use quarkusDev#workingDirectory</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/5497f75d28597d01dd450e0e6efe4b607f5404a7"><code>5497f75</code></a>
Move the import of smallrye-common-bom higher up to make sure other BOMs
don'...</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/7b50fb998b901beb000da27137417da50cdf0422"><code>7b50fb9</code></a>
Properly convert MemorySize to RESTEasy configuration</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/247cb85a2e9da3a3ef4296e6825ff36142016c87"><code>247cb85</code></a>
Introduce option for multipartPostEncoderMode in REST Client
builder</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/b5095e099b5e966a3dd388040f34c0314ccaf730"><code>b5095e0</code></a>
Add note about multipart encoder mode in the docs</li>
<li>Additional commits viewable in <a
href="https://github.com/quarkusio/quarkus/compare/3.9.1...3.9.2">compare
view</a></li>
</ul>
</details>
<br />

Updates `io.quarkus:quarkus-maven-plugin` from 3.9.1 to 3.9.2

Updates `io.quarkus:quarkus-extension-processor` from 3.9.1 to 3.9.2

Updates `io.quarkus:quarkus-extension-maven-plugin` from 3.9.1 to 3.9.2
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/quarkusio/quarkus/releases">io.quarkus:quarkus-extension-maven-plugin's
releases</a>.</em></p>
<blockquote>
<h2>3.9.2</h2>
<h3>Complete changelog</h3>
<ul>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/38964">#38964</a>
- Add smallrye metrics capability</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39668">#39668</a>
- Recompute cache when the redis connection pool is exhausted</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39705">#39705</a>
- WebSockets Next: error handlers part 1</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/39717">#39717</a>
- OIDC code flow access token verification is enforced even if the
application code does not use it as JWT</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39718">#39718</a>
- Enforce OIDC code flow access token verification only if JWT is in the
application code</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39725">#39725</a>
- Setting the correct CodeFlowVerifyAccessTokenDisabledTest test class
name</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39742">#39742</a>
- Fix a remaining reference to quarkus.resteasy-reactive. prefix</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/39746">#39746</a>
- ScheduledExecutorService: cannot remove future task from the
scheduler</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39763">#39763</a>
- WebSockets Next: error handlers part 2</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39766">#39766</a>
- Properly handle array class types to be looked up</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39770">#39770</a>
- Improve the multipart encoded mode handling in the rest client</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/39776">#39776</a>
- Cannot build native image after 3.9.1 upgrade - missing configuration
properties but they exist</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/39777">#39777</a>
- Bean Param init issue - java.lang.NoClassDefFoundError:
io/quarkus/generated/int$quarkusrestparamConverter$</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39790">#39790</a>
- Add quarkus-credentials-deployment where it's missing</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39794">#39794</a>
- Bump org.jboss.threads:jboss-threads from 3.6.0.Final to
3.6.1.Final</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39797">#39797</a>
- Docs: fix typo in OIDC tenant resolution by configuration</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/39798">#39798</a>
- Update documentation for QUARKUS AND GRADLE - Development mode:
quarkusDev#workingDir has been deprecated</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39804">#39804</a>
- Always record profiles</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39823">#39823</a>
- Ensure ParameterConverter is loaded from the TCCL</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39829">#39829</a>
- Use quarkusDev#workingDirectory</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/39835">#39835</a>
- Bump maven-model-helper to 36</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/quarkusio/quarkus/commit/69864c3440d97dc19fb7f81459cd445b60a8b777"><code>69864c3</code></a>
[RELEASE] - Bump version to 3.9.2</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/7d4d8e1127d7846add5268ddd88b414c0d7ea1cf"><code>7d4d8e1</code></a>
Merge pull request <a
href="https://redirect.github.com/quarkusio/quarkus/issues/39845">#39845</a>
from gsmet/3.9.2-backports-1</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/cc5ab4b1be581ab30f02a50ac3fa46e1a3f2ff03"><code>cc5ab4b</code></a>
Add smallrye metrics capability</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/93e7782acb7b1531fb798aa930662892d4ce087f"><code>93e7782</code></a>
Bump maven-model-helper to 36</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/4043c0e7f82541cef3cb12cdd376ab76c42ba03d"><code>4043c0e</code></a>
Ensure ParameterConverter is loaded from the TCCL</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/8cdead9234433c58b367f2cf122a73948509bfbb"><code>8cdead9</code></a>
Use quarkusDev#workingDirectory</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/5497f75d28597d01dd450e0e6efe4b607f5404a7"><code>5497f75</code></a>
Move the import of smallrye-common-bom higher up to make sure other BOMs
don'...</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/7b50fb998b901beb000da27137417da50cdf0422"><code>7b50fb9</code></a>
Properly convert MemorySize to RESTEasy configuration</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/247cb85a2e9da3a3ef4296e6825ff36142016c87"><code>247cb85</code></a>
Introduce option for multipartPostEncoderMode in REST Client
builder</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/b5095e099b5e966a3dd388040f34c0314ccaf730"><code>b5095e0</code></a>
Add note about multipart encoder mode in the docs</li>
<li>Additional commits viewable in <a
href="https://github.com/quarkusio/quarkus/compare/3.9.1...3.9.2">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>